# Generated by Django 3.2.5 on 2021-10-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ff_League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('current_week', models.IntegerField()),
                ('nfl_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('playerID', models.IntegerField()),
                ('posRank', models.IntegerField()),
                ('acquisitionType', models.CharField(max_length=64)),
                ('proTeam', models.CharField(max_length=6)),
                ('position', models.CharField(max_length=64)),
                ('injuryStatus', models.CharField(max_length=64)),
                ('injured', models.BooleanField()),
                ('total_points', models.IntegerField()),
                ('projected_total_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('team_abbrev', models.CharField(max_length=6)),
                ('team_name', models.CharField(max_length=64)),
                ('division_id', models.CharField(max_length=64)),
                ('division_name', models.CharField(max_length=64)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('points_for', models.IntegerField()),
                ('points_agaisnt', models.IntegerField()),
                ('owner', models.CharField(max_length=64)),
                ('streak_type', models.CharField(max_length=16)),
                ('streak_length', models.IntegerField()),
                ('standing', models.IntegerField()),
                ('final_standings', models.IntegerField()),
                ('logo_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_season_count', models.IntegerField()),
                ('veto_votes_required', models.IntegerField()),
                ('team_count', models.IntegerField()),
                ('playoff_team_count', models.IntegerField()),
                ('keeper_count', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('tie_rule', models.IntegerField(blank=True, null=True)),
                ('playoff_seed_tie_rule', models.IntegerField(blank=True, null=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FFB_Website.ff_league')),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='FFB_Website.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='FFB_Website.team')),
            ],
        ),
        migrations.CreateModel(
            name='BoxScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField()),
                ('home_projected', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('away_projected', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_away_team', to='FFB_Website.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_home_team', to='FFB_Website.team')),
            ],
        ),
    ]
